name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '💥 Breaking'
    label: 'breaking'
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📦 Dependency Updates'
    labels:
      - 'dependencies'
    collapse-after: 15
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '✍️ Other changes'
exclude-labels:
  - 'skip-changelog'
  - 'invalid'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feat\/.+/'
    title:
      - '/feat\/.+/'
