---
name: Bug report
about: Report a bug or issue with the Gradle Convention plugin for Jenkins plugin development
title: ''
labels: bug
assignees: ''
---

<!-- Before submitting, please ensure:
     - You are using the latest version of the convention plugin.
     - You have tested with Gradle 9.x, Kotlin 2.1+, and Java 17+.
     - You have checked the documentation and searched for similar issues.
-->

**Describe the bug**

<!-- Clearly describe the bug or unexpected behavior. What is happening? What should happen? -->

**To Reproduce**

<!-- Steps to reproduce the problem. Please provide a minimal, reproducible example if possible.
1. Provide your `build.gradle(.kts)` or relevant configuration snippet.
2. List the precise Gradle command(s) used.
3. Describe the Jenkins plugin project structure or point to a minimal repository (if possible).
4. Include any relevant logs or stack traces.
-->

**Expected behavior**

<!-- What did you expect the plugin to do? -->

**Screenshots or Logs**

<!-- If applicable, add screenshots or copy relevant logs/stack traces here. Use code blocks for multiline logs. -->

**Environment**

- Gradle version: 
- Convention plugin version:
- Jenkins plugin version:
- Java version:
- Kotlin version (if applicable):
- OS and version:

**Additional context**

<!-- Any other information, configuration, or links that may help us debug the issue. -->
