name: Feature Request
description: Suggest an idea for the Jenkins Gradle Convention Plugin
title: "[Feature] "
labels: [ "type: enhancement", "status: needs-triage" ]
body:
    -   type: markdown
        attributes:
            value: |
                Thanks for taking the time to fill out this bug report! Please fill out the form below with as much detail as possible.

                Before submitting, please check if a similar issue already exists.

    -   type: checkboxes
        id: checks
        attributes:
            label: Initial Checks
            options:
                -   label: I have searched the existing issues to ensure this is not a duplicate
                    required: true
                -   label: I am using the latest version of the plugin
                    required: false
                -   label: This feature would be useful to others, not just for my specific use case
                    required: false

    -   type: textarea
        id: problem
        attributes:
            label: Problem Statement
            description: Is your feature request related to a problem? Please describe.
            placeholder: "I'm always frustrated when [...]"
        validations:
            required: true

    -   type: textarea
        id: solution
        attributes:
            label: Proposed Solution
            description: Describe the solution you'd like
            placeholder: "I would like to see [...]"
        validations:
            required: true

    -   type: textarea
        id: alternatives
        attributes:
            label: Alternatives Considered
            description: Describe the alternatives you've considered
            placeholder: "I've considered [...]"
        validations:
            required: false

    -   type: textarea
        id: context
        attributes:
            label: Additional Context
            description: Add any other context, screenshots, or examples about the feature support
        validations:
            required: false

    -   type: dropdown
        id: priority
        attributes:
            label: Perceived Priority
            description: How important you feel this feature is?
            options:
                - Critical (blocking work)
                - High (major improvement)
                - Medium (significant enhancement)
                - Low (nice to have)
            default: 1
        validations:
            required: true

    -   type: dropdown
        id: willingness
        attributes:
            label: Contribution Willingness
            description: Would you be willing to contribute to this feature?
            options:
                - Yes, I'd would implement this
                - I could help with part of it
                - I can test but not implement
                - No, I'm just suggesting
            default: 3
        validations:
            required: false
