name: CI
permissions:
  contents: read
  packages: write
  actions: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-analyze:
    name: Build & analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant executable permissions for gradlew
        run: chmod +x gradlew

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Clean, build & analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew clean build sonar --no-daemon --stacktrace --info

      - name: Publish to Maven Local
        run: |
          ./gradlew publishtoLocal

      - name: Build the "git-automerger-plugin"
        run: |
          cd ./examples/git-automerger-plugin && chmod +x gradlew && ./gradlew clean build --no-daemon --no-configuration-cache -x test --stacktrace
