name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build-test-analyze:
    name: Build & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin

      - name: Build & Test
        run: |
          ./gradlew clean build --no-daemon --stacktrace -Dkotlin.incremental.classpath.diff.enabled=false

      - name: Publish to Maven Local
        run: |
          ./gradlew publishToLocal --no-daemon --stacktrace

      - name: Build Git Automerger Plugin Example
        run: |
          cd ./examples/git-automerger-plugin
          ./gradlew clean build --no-configuration-cache -x test --no-daemon --stacktrace

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
